# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2024-12-14T01:49:21+00:00

from __future__ import annotations

from datetime import date, datetime
from typing import List, Optional

from pydantic import AnyUrl, BaseModel


class CaseDetails(BaseModel):
    ocdCaseTypeId: str
    ocdCaseSubTypeId: str
    ocdWorkflowId: str
    ocdAssignerId: str
    ocdAssignedDate: datetime
    ocdAssigneeId: str
    ocdStatusId: str
    ocdActionId: str
    ocdIsEditable: bool


class Organisation(BaseModel):
    tempId: str
    organisationName: str
    acronym: Optional[str]
    organisationType: str
    mission: str
    objectives: str
    vision: str
    logo: AnyUrl
    testField: Optional[str]


class Address(BaseModel):
    tempId: str
    address1: str
    address2: Optional[str]
    address3: Optional[str]
    addressType: str
    country: str
    postalCode: str
    startDate: datetime
    endDate: datetime


class IdentifierItem(BaseModel):
    tempId: str
    identifierValue: str
    issueDate: date
    expiryDate: date
    identifierType: str
    issuedBy: str
    organisation: str


class ContactItem(BaseModel):
    tempId: str
    contactType: str
    contactValue: str
    isPrimary: bool


class ContactPersonItem(BaseModel):
    tempId: str
    firstName: str
    lastName: str
    assignedPerson: str
    address: str
    organisation: str
    role: str
    role1: Optional[str]


class ActivityItem(BaseModel):
    tempId: str
    activityName: str
    type: str
    startDate: date
    endDate: date
    description: str


class FinancialInformation(BaseModel):
    tempId: str
    dateFrom: date
    dateTo: date
    accountType: str
    amount: float
    address: str


class FormDataSchema(BaseModel):
    CaseDetails: CaseDetails
    Organisation: Organisation
    Address: List[Address]
    Identifier: List[IdentifierItem]
    Contact: List[ContactItem]
    ContactPerson: List[ContactPersonItem]
    Activity: List[ActivityItem]
    FinancialInformation: List[FinancialInformation]
